checkpoint_dir: checkpoints/mistralai/Mistral-7B-v0.1
out_dir: out/qlora-mistral-7b-custom-data
precision: bf16-true
quantize: bnb.nf4-dq
devices: 1
lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_query: true
lora_key: false
lora_value: true
lora_projection: false
lora_mlp: false
lora_head: false
data:
  class_path: litgpt.data.JSON
  init_args:
    json_path: data/custom
    mask_prompt: false
    prompt_style: alpaca
    ignore_index: -100
    seed: 42
    num_workers: 4
train:
  save_interval: 500
  log_interval: 10
  global_batch_size: 16
  micro_batch_size: 4
  lr_warmup_steps: 100
  epochs: 1
  max_seq_length: 1024
  learning_rate: 0.0001
  weight_decay: 0.01
  beta1: 0.9
  beta2: 0.95
  min_lr: 1.0e-05
eval:
  interval: 500
  max_new_tokens: 150
  max_iters: 50
logger_name: tensorboard
seed: 1337
