# RAG System Configuration
# Main configuration file for the entertainment RAG system

# System Settings
system:
  name: "Entertainment RAG System"
  version: "1.1"
  description: "Movie-savvy RAG system with Reddit integration for entertainment queries"

# Data Configuration
data:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  reddit_dir: "data/processed/reddit_data"  # Directory for Reddit data
  categories:
    - "anime"
    - "manga"
    - "bollywood"
    - "hollywood"
    - "kdrama"
    - "kmovie"
  preprocessing:
    chunk_size: 512
    chunk_overlap: 50
    output_file: "processed_chunks.jsonl"
    metadata_file: "metadata.json"
    log_file: "preprocess_log.txt"

# Reddit Configuration
reddit:
  trigger_keywords:
    - "reddit"
    - "discussion"
    - "people think"
    - "community"
    - "opinions"
    - "users say"
  scraper:
    max_posts: 3  # Number of Reddit posts to retrieve
    output_file: "reddit_results.jsonl"  # Output for scraped data
    log_file: "reddit_scraper.log"  # Reddit-specific logging
    embedding_cache: true  # Use in-memory embeddings for speed

# Retrieval Configuration
retrieval:
  embedding_model: "all-MiniLM-L6-v2"
  embedding_dimension: 384
  index:
    type: "faiss"
    index_file: "index.bin"
    metadata_file: "index_metadata.json"
    save_dir: "retrieval/index"
  top_k: 8
  similarity_threshold: 0.3  # Adjusted to match run_rag.py Reddit fallback
  max_retrieved_tokens: 3000

# Generation Configuration
generation:
  model:
    name: "mistral-7b-finetuned"
    path: "models/mistral-7b-finetuned"
    checkpoint_file: "lit_model.pth"
    lora_file: "lit_model.pth.lora"
    config_file: "config.json"
  parameters:
    max_new_tokens: 512
    temperature: 0.7
    top_k: 60
    repetition_penalty: 1.2
    do_sample: true
    quantize: null
  prompt:
    template_dir: "generation/prompt_templates"
    default_prompt_file: "rag_prompt.txt"  # Updated: Changed from default_template
    reddit_prompt_file: "rag_reddit_prompt.txt"  # Updated: Changed from reddit_template
    style: "movie_savvy"
    max_context_length: 8192
  history_window: 5

# Pipeline Configuration
pipeline:
  batch_size: 1
  timeout: 300
  logging:
    level: "INFO"
    log_dir: "output/logs"
    log_file: "rag_pipeline.log"
    reddit_log_file: "reddit_pipeline.log"  # Reddit-specific logging
  output:
    results_dir: "output/results"
    save_intermediate: true
    result_format: "json"

# Performance Settings
performance:
  device: "cuda"
  max_memory_mb: 4096
  cache_embeddings: true
  cache_retrievals: false
  num_workers: 4
  multiprocessing: false

# Validation Settings
validation:
  test_queries:
    - "Find anime similar to Berserk with dark themes"
    - "Compare Monkey D. Luffy and Eren Yeager character development"
    - "How does Pushpa Raj evolve in Pushpa 2: The Rule"
    - "What do people think about Train to Busan on Reddit"  # Reddit-triggered query
  metrics:
    - "retrieval_time"
    - "generation_time"
    - "total_time"
    - "relevance_score"