data:
  categories:
  - anime
  - manga
  - bollywood
  - hollywood
  - kdrama
  - kmovie
  preprocessing:
    chunk_overlap: 50
    chunk_size: 512
    embedding_stats_file: embedding_stats.json
    log_file: preprocess_log.txt
    metadata_file: metadata.json
    output_file: processed_chunks.jsonl
    stats_file: processing_stats.json
  processed_dir: rag_system/data/processed
  raw_dir: rag_system/data/raw
  reddit_dir: data/processed/reddit_data
generation:
  history_window: 5
  model:
    checkpoint_file: lit_model.pth
    config_file: config.json
    lora_file: lit_model.pth.lora
    name: mistral-7b-finetuned
    path: models/mistral-7b-finetuned
  parameters:
    do_sample: true
    max_new_tokens: 1024
    quantize: null
    repetition_penalty: 1.2
    temperature: 0.7
    top_k: 50
  prompt:
    default_prompt_file: rag_prompt.txt
    max_context_length: 16384
    reddit_prompt_file: rag_reddit_prompt.txt
    style: movie_savvy
    template_dir: generation/prompt_templates
performance:
  cache_embeddings: true
  cache_retrievals: false
  device: cuda
  max_memory_mb: 8192
  multiprocessing: false
  num_workers: 4
pipeline:
  batch_size: 1
  logging:
    level: INFO
    log_dir: output/logs
    log_file: rag_pipeline.log
    reddit_log_file: reddit_pipeline.log
  output:
    result_format: json
    results_dir: output/results
    save_intermediate: true
  timeout: 300
reddit:
  scraper:
    embedding_cache: true
    log_file: reddit_scraper.log
    max_posts: 2
    output_file: reddit_results.jsonl
  trigger_keywords:
  - reddit
  - discussion
  - people think
  - community
  - opinions
  - users say
retrieval:
  embedding_dimension: 1024
  embedding_model: intfloat/e5-large-v2
  index:
    index_file: index.bin
    metadata_file: index_metadata.json
    save_dir: retrieval/index
    type: faiss
  max_retrieved_tokens: 4000
  similarity_threshold: 0.4
  top_k: 4
system:
  description: Movie-savvy RAG system with Reddit integration for entertainment queries
  name: Entertainment RAG System
  version: '1.1'
validation:
  metrics:
  - retrieval_time
  - generation_time
  - total_time
  - relevance_score
  test_queries:
  - Find anime similar to Berserk with dark themes
  - Compare Monkey D. Luffy and Eren Yeager character development
  - 'How does Pushpa Raj evolve in Pushpa 2: The Rule'
  - What do people think about Train to Busan on Reddit
